### ISSUE TITLE
Issue with subtitleedit autotranslations

### ISSUE THREAD

**Issue by Alihkhawaher** [thammegowda/nllb-serve#17]
Dears after I updated today, I was unable to translate to Arabic using subtitleedit, the translated text are gibberish /0xxx codes

I returned nllb-serve to commit 640b31e and now it is fine. I do not know why, but I know that it is because of the recent changes.

Note, the translation using the webpage is fine.

Thanks

**Comment by thammegowda** [comment]
@Alihkhawaher  Thanks for reporting!
We upgrade a underlying library (Flask v2.x -> v3.x) which broke the way unicode text is handled in JSON output. 
Thanks @sgowdaks for fixing it in #18

**Comment by thammegowda** [comment]
@Alihkhawaher please let us know here if you face the encoding issue after upgrading to newest version!

**Comment by Alihkhawaher** [comment]
Yes, I did git pull and pip -r requirements.txt --upgrade

Now translation in subtitleedit works fine.

Many thanks
