### ISSUE TITLE
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by erikvullings** [thammegowda/nllb-serve#9]
See here for a [solution](https://stackoverflow.com/questions/77213053/importerror-cannot-import-name-url-quote-from-werkzeug-urls).

In requirements.txt, specify Werkzeug==2.2.2

**Comment by thammegowda** [comment]
Thanks. Upgraded Flask to 3.x and added explicit version number for Werkzeug in requirements.txt 
this issue is fixed now.
